// Migração aditiva: executada somente ao acessar a API Tech.
export const TECH_TABLES = ['tech_categorias', 'tech_servicos', 'tech_solicitacoes', 'tech_orcamentos', 'tech_ordens', 'tech_ordem_itens', 'tech_fotos', 'tech_historico', 'tech_pagamentos', 'tech_despesas', 'tech_aditivos', 'tech_auditoria', 'tech_limites'];
export async function ensureTechSchema(env) {
  const sql = [
    `CREATE TABLE IF NOT EXISTS tech_categorias (id INTEGER PRIMARY KEY AUTOINCREMENT, nome TEXT NOT NULL, descricao TEXT NOT NULL DEFAULT '', campos_json TEXT NOT NULL DEFAULT '[]', ativo INTEGER NOT NULL DEFAULT 1, excluido INTEGER NOT NULL DEFAULT 0)`,
    `CREATE TABLE IF NOT EXISTS tech_servicos (id INTEGER PRIMARY KEY AUTOINCREMENT, categoria_id INTEGER NOT NULL REFERENCES tech_categorias(id), nome TEXT NOT NULL, descricao TEXT NOT NULL DEFAULT '', imagem_url TEXT NOT NULL DEFAULT '', tipo_preco TEXT NOT NULL DEFAULT 'orcamento', preco_centavos INTEGER NOT NULL DEFAULT 0, tempo TEXT NOT NULL DEFAULT '', materiais TEXT NOT NULL DEFAULT '', garantia TEXT NOT NULL DEFAULT '', observacoes TEXT NOT NULL DEFAULT '', campos_json TEXT NOT NULL DEFAULT '[]', ativo INTEGER NOT NULL DEFAULT 1, excluido INTEGER NOT NULL DEFAULT 0)`,
    `CREATE TABLE IF NOT EXISTS tech_solicitacoes (id INTEGER PRIMARY KEY AUTOINCREMENT, chave_envio TEXT NOT NULL UNIQUE, cliente_id INTEGER REFERENCES clientes(id), servico_id INTEGER NOT NULL REFERENCES tech_servicos(id), servico_nome TEXT NOT NULL, nome TEXT NOT NULL, telefone TEXT NOT NULL, endereco TEXT NOT NULL, localizacao TEXT NOT NULL DEFAULT '', descricao TEXT NOT NULL, quantidade INTEGER NOT NULL, prioridade TEXT NOT NULL DEFAULT 'Normal', data_desejada TEXT, preferencia TEXT NOT NULL DEFAULT '', observacoes TEXT NOT NULL DEFAULT '', respostas_json TEXT NOT NULL DEFAULT '[]', fotos_json TEXT NOT NULL DEFAULT '[]', status TEXT NOT NULL DEFAULT 'Novo', criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS tech_orcamentos (id INTEGER PRIMARY KEY AUTOINCREMENT, solicitacao_id INTEGER NOT NULL UNIQUE REFERENCES tech_solicitacoes(id), token TEXT NOT NULL UNIQUE, itens_json TEXT NOT NULL, desconto_centavos INTEGER NOT NULL DEFAULT 0, total_centavos INTEGER NOT NULL, validade TEXT NOT NULL, prazo TEXT NOT NULL, garantia TEXT NOT NULL DEFAULT '', observacoes TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'Orçamento preparado', versao INTEGER NOT NULL DEFAULT 1, criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, enviado_em TEXT, decidido_em TEXT)`,
    `CREATE TABLE IF NOT EXISTS tech_ordens (id INTEGER PRIMARY KEY AUTOINCREMENT, numero TEXT NOT NULL UNIQUE, token_publico TEXT NOT NULL UNIQUE, solicitacao_id INTEGER NOT NULL REFERENCES tech_solicitacoes(id), orcamento_id INTEGER NOT NULL UNIQUE REFERENCES tech_orcamentos(id), cliente_id INTEGER REFERENCES clientes(id), status TEXT NOT NULL DEFAULT 'Aguardando agendamento', responsavel TEXT NOT NULL DEFAULT '', endereco TEXT NOT NULL, telefone TEXT NOT NULL, servico_nome TEXT NOT NULL, descricao TEXT NOT NULL, itens_json TEXT NOT NULL, total_centavos INTEGER NOT NULL, pago_centavos INTEGER NOT NULL DEFAULT 0, agendado_para TEXT, inicio_em TEXT, concluido_em TEXT, observacoes TEXT NOT NULL DEFAULT '', criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, atualizado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS tech_ordem_itens (id INTEGER PRIMARY KEY AUTOINCREMENT, ordem_id INTEGER NOT NULL REFERENCES tech_ordens(id), tipo TEXT NOT NULL, nome TEXT NOT NULL, produto_id INTEGER REFERENCES produtos(id), quantidade REAL NOT NULL, quantidade_utilizada REAL NOT NULL DEFAULT 0, custo_centavos INTEGER NOT NULL DEFAULT 0, reposicao_centavos INTEGER NOT NULL DEFAULT 0, preco_centavos INTEGER NOT NULL DEFAULT 0, subtotal_centavos INTEGER NOT NULL DEFAULT 0)`,
    `CREATE TABLE IF NOT EXISTS tech_fotos (id INTEGER PRIMARY KEY AUTOINCREMENT, ordem_id INTEGER NOT NULL REFERENCES tech_ordens(id), etapa TEXT NOT NULL CHECK(etapa IN ('antes','depois')), url TEXT NOT NULL, public_id TEXT NOT NULL DEFAULT '', criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS tech_historico (id INTEGER PRIMARY KEY AUTOINCREMENT, ordem_id INTEGER NOT NULL REFERENCES tech_ordens(id), tipo TEXT NOT NULL, descricao TEXT NOT NULL, dados_json TEXT NOT NULL DEFAULT '{}', criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS tech_pagamentos (id INTEGER PRIMARY KEY AUTOINCREMENT, ordem_id INTEGER NOT NULL REFERENCES tech_ordens(id), chave TEXT NOT NULL UNIQUE, valor_centavos INTEGER NOT NULL, metodo TEXT NOT NULL, observacoes TEXT NOT NULL DEFAULT '', caixa_id INTEGER, criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS tech_despesas (id INTEGER PRIMARY KEY AUTOINCREMENT, ordem_id INTEGER NOT NULL REFERENCES tech_ordens(id), chave TEXT NOT NULL UNIQUE, categoria TEXT NOT NULL, descricao TEXT NOT NULL, valor_centavos INTEGER NOT NULL, caixa_id INTEGER, criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS tech_aditivos (id INTEGER PRIMARY KEY AUTOINCREMENT, ordem_id INTEGER NOT NULL REFERENCES tech_ordens(id), token TEXT NOT NULL UNIQUE, itens_json TEXT NOT NULL, total_centavos INTEGER NOT NULL, motivo TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'Aguardando aprovação', versao INTEGER NOT NULL DEFAULT 1, criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, decidido_em TEXT)`,
    `CREATE TABLE IF NOT EXISTS tech_auditoria (id INTEGER PRIMARY KEY AUTOINCREMENT, entidade TEXT NOT NULL, entidade_id INTEGER NOT NULL, evento TEXT NOT NULL, dados_json TEXT NOT NULL DEFAULT '{}', criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
    `CREATE TABLE IF NOT EXISTS tech_limites (chave TEXT PRIMARY KEY, janela INTEGER NOT NULL, quantidade INTEGER NOT NULL)`,
    `CREATE INDEX IF NOT EXISTS idx_tech_solicitacoes_cliente ON tech_solicitacoes(cliente_id)`,
    `CREATE INDEX IF NOT EXISTS idx_tech_servicos_categoria ON tech_servicos(categoria_id)`,
    `CREATE INDEX IF NOT EXISTS idx_tech_ordens_status ON tech_ordens(status, agendado_para)`,
    `CREATE INDEX IF NOT EXISTS idx_tech_ordens_cliente ON tech_ordens(cliente_id)`,
    `CREATE INDEX IF NOT EXISTS idx_tech_historico_ordem ON tech_historico(ordem_id, criado_em)`,
    `CREATE INDEX IF NOT EXISTS idx_tech_fotos_ordem ON tech_fotos(ordem_id, etapa, criado_em)`,
    `CREATE TRIGGER IF NOT EXISTS trg_tech_estoque_suficiente BEFORE UPDATE OF status ON tech_ordens WHEN NEW.status='Concluído' AND OLD.status<>'Concluído' AND EXISTS(SELECT 1 FROM (SELECT produto_id,SUM(quantidade_utilizada) quantidade FROM tech_ordem_itens WHERE ordem_id=NEW.id AND produto_id IS NOT NULL GROUP BY produto_id) i JOIN produtos p ON p.id=i.produto_id WHERE i.quantidade>p.estoque) BEGIN SELECT RAISE(ABORT, 'estoque_insuficiente'); END`,
    `CREATE TRIGGER IF NOT EXISTS trg_tech_baixa_estoque AFTER UPDATE OF status ON tech_ordens WHEN NEW.status='Concluído' AND OLD.status<>'Concluído' BEGIN UPDATE produtos SET estoque=estoque-(SELECT CAST(SUM(i.quantidade_utilizada) AS INTEGER) FROM tech_ordem_itens i WHERE i.ordem_id=NEW.id AND i.produto_id=produtos.id), atualizado_em=CURRENT_TIMESTAMP WHERE id IN (SELECT produto_id FROM tech_ordem_itens WHERE ordem_id=NEW.id AND produto_id IS NOT NULL AND quantidade_utilizada>0); INSERT INTO movimentacoes_estoque(produto_id,tipo,quantidade,estoque_anterior,estoque_novo,motivo,ordem_servico_id) SELECT i.produto_id,'saida',CAST(SUM(i.quantidade_utilizada) AS INTEGER),p.estoque+CAST(SUM(i.quantidade_utilizada) AS INTEGER),p.estoque,'Ordem de serviço '||NEW.numero,NEW.id FROM tech_ordem_itens i JOIN produtos p ON p.id=i.produto_id WHERE i.ordem_id=NEW.id AND i.quantidade_utilizada>0 GROUP BY i.produto_id; END`
  ];
  await env.DB.batch(sql.map(s => env.DB.prepare(s)));
  const cols=await env.DB.prepare('PRAGMA table_info(tech_solicitacoes)').all(), existing=new Set((cols.results||[]).map(c=>c.name));
  for(const [name,type] of [['prioridade',"TEXT NOT NULL DEFAULT 'Normal'"],['data_desejada','TEXT'],['localizacao',"TEXT NOT NULL DEFAULT ''"]])if(!existing.has(name))await env.DB.prepare(`ALTER TABLE tech_solicitacoes ADD COLUMN ${name} ${type}`).run();
  const orderCols=await env.DB.prepare('PRAGMA table_info(tech_ordens)').all(), orderNames=new Set((orderCols.results||[]).map(c=>c.name));
  if(!orderNames.has('token_publico')){await env.DB.prepare('ALTER TABLE tech_ordens ADD COLUMN token_publico TEXT').run();await env.DB.prepare(`UPDATE tech_ordens SET token_publico=lower(hex(randomblob(32))) WHERE token_publico IS NULL OR token_publico=''`).run();}
  await env.DB.prepare(`CREATE UNIQUE INDEX IF NOT EXISTS idx_tech_ordens_token_publico ON tech_ordens(token_publico) WHERE token_publico IS NOT NULL AND token_publico<>''`).run();
}
